name: Trigger Empty Commit on Issue Update

on:
  issue_comment:
    types: [created, edited]
  workflow_dispatch:  # 手动触发入口

jobs:
  trigger-empty-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check if manual trigger or target issue
        id: check-trigger
        run: |
          # 如果是手动触发
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "should_trigger=true" >> $GITHUB_OUTPUT
          # 如果是 issue_comment 事件且针对 issue #1
          elif [ "${{ github.event.issue.number }}" == "1" ]; then
            echo "should_trigger=true" >> $GITHUB_OUTPUT
          else
            echo "should_trigger=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger empty commit in lawtee.github.io
        if: steps.check-trigger.outputs.should_trigger == 'true'
        uses: actions/github-script@v6
        env:
          PAT: ${{ secrets.PAT }}
        with:
          script: |
            const { execSync } = require('child_process');
            const repo = 'h2dcc/lawtee.github.io';
            const token = process.env.PAT;

            try {
              const repoUrl = `https://x-access-token:${token}@github.com/${repo}.git`;
              execSync(`git clone ${repoUrl}`);
              process.chdir('lawtee.github.io');

              execSync('git config user.name "github-actions[bot]"');
              execSync('git config user.email "41898282+github-actions[bot]@users.noreply.github.com"');

              // 添加手动触发的标识
              const commitMsg = "${{ github.event_name == 'workflow_dispatch' ? 
                '[Manual] Trigger update from moments/issues/1' : 
                'Trigger update from moments/issues/1' }}";
              
              execSync(`git commit --allow-empty -m "${commitMsg}"`);
              execSync(`git push ${repoUrl} master`);
              console.log('✅ Empty commit pushed successfully!');
            } catch (error) {
              console.error('❌ Error:', error.message);
              process.exit(1);
            }
