name: Trigger Empty Commit on Issue Update

on:
  issue_comment:
    types: [created, edited]

jobs:
  trigger-empty-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the comment is on the target issue
        id: check-issue
        run: |
          # 确保只对 issues/1 的评论触发
          if [ "${{ github.event.issue.number }}" != "1" ]; then
            echo "::set-output name=should_trigger::false"
          else
            echo "::set-output name=should_trigger::true"
          fi

      - name: Trigger empty commit in lawtee.github.io
        if: steps.check-issue.outputs.should_trigger == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { execSync } = require('child_process');
            const repo = 'h2dcc/lawtee.github.io';
            const token = process.env.GITHUB_TOKEN;

            // 克隆目标仓库
            execSync(`git clone https://github.com/${repo}.git`);
            process.chdir('lawtee.github.io');

            // 设置 Git 身份
            execSync('git config user.name "github-actions[bot]"');
            execSync('git config user.email "41898282+github-actions[bot]@users.noreply.github.com"');

            // 创建一个空提交并推送
            execSync('git commit --allow-empty -m "Trigger update from moments/issues/1"');
            execSync(`git push https://${token}@github.com/${repo}.git master`);
